
/**
 *
 * @author ADM
 */
public class Choix extends javax.swing.JFrame {

   
    public Choix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        B7_1 = new javax.swing.JRadioButton();
        B7_2 = new javax.swing.JRadioButton();
        B7_3 = new javax.swing.JRadioButton();
        B6_1 = new javax.swing.JRadioButton();
        B6_2 = new javax.swing.JRadioButton();
        B6_3 = new javax.swing.JRadioButton();
        B5_1 = new javax.swing.JRadioButton();
        B5_2 = new javax.swing.JRadioButton();
        B5_3 = new javax.swing.JRadioButton();
        B4_1 = new javax.swing.JRadioButton();
        B4_2 = new javax.swing.JRadioButton();
        B4_3 = new javax.swing.JRadioButton();
        B3_3 = new javax.swing.JRadioButton();
        B3_2 = new javax.swing.JRadioButton();
        B3_1 = new javax.swing.JRadioButton();
        B2_1 = new javax.swing.JRadioButton();
        B2_2 = new javax.swing.JRadioButton();
        B2_3 = new javax.swing.JRadioButton();
        B1_1 = new javax.swing.JRadioButton();
        B1_2 = new javax.swing.JRadioButton();
        B1_3 = new javax.swing.JRadioButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        buttonGroup8.add(jRadioButton24);
        jRadioButton24.setForeground(new java.awt.Color(204, 255, 204));
        jRadioButton24.setText("Debutant");
        jRadioButton24.setOpaque(false);
        jPanel1.add(jRadioButton24);
        jRadioButton24.setBounds(380, 480, 90, 23);

        buttonGroup8.add(jRadioButton23);
        jRadioButton23.setForeground(new java.awt.Color(204, 255, 204));
        jRadioButton23.setText("Intermediaire");
        jRadioButton23.setOpaque(false);
        jPanel1.add(jRadioButton23);
        jRadioButton23.setBounds(380, 500, 130, 23);

        buttonGroup8.add(jRadioButton22);
        jRadioButton22.setForeground(new java.awt.Color(204, 255, 204));
        jRadioButton22.setText("Avancée");
        jRadioButton22.setOpaque(false);
        jPanel1.add(jRadioButton22);
        jRadioButton22.setBounds(380, 520, 90, 23);

        buttonGroup7.add(B7_1);
        B7_1.setForeground(new java.awt.Color(204, 255, 204));
        B7_1.setText("Debutant");
        B7_1.setOpaque(false);
        B7_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B7_1MouseClicked(evt);
            }
        });
        jPanel1.add(B7_1);
        B7_1.setBounds(180, 480, 90, 23);

        buttonGroup7.add(B7_2);
        B7_2.setForeground(new java.awt.Color(204, 255, 204));
        B7_2.setText("Intermediaire");
        B7_2.setOpaque(false);
        B7_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B7_2MouseClicked(evt);
            }
        });
        jPanel1.add(B7_2);
        B7_2.setBounds(180, 500, 130, 23);

        buttonGroup7.add(B7_3);
        B7_3.setForeground(new java.awt.Color(204, 255, 204));
        B7_3.setText("Avancée");
        B7_3.setOpaque(false);
        B7_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B7_3MouseClicked(evt);
            }
        });
        B7_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7_3ActionPerformed(evt);
            }
        });
        jPanel1.add(B7_3);
        B7_3.setBounds(180, 520, 90, 23);

        buttonGroup6.add(B6_1);
        B6_1.setForeground(new java.awt.Color(204, 255, 204));
        B6_1.setText("Debutant");
        B6_1.setOpaque(false);
        B6_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6_1MouseClicked(evt);
            }
        });
        jPanel1.add(B6_1);
        B6_1.setBounds(490, 370, 90, 23);

        buttonGroup6.add(B6_2);
        B6_2.setForeground(new java.awt.Color(204, 255, 204));
        B6_2.setText("Intermediaire");
        B6_2.setOpaque(false);
        B6_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6_2MouseClicked(evt);
            }
        });
        jPanel1.add(B6_2);
        B6_2.setBounds(490, 390, 120, 23);

        buttonGroup6.add(B6_3);
        B6_3.setForeground(new java.awt.Color(204, 255, 204));
        B6_3.setText("Avancée");
        B6_3.setOpaque(false);
        B6_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6_3MouseClicked(evt);
            }
        });
        jPanel1.add(B6_3);
        B6_3.setBounds(490, 410, 90, 23);

        buttonGroup5.add(B5_1);
        B5_1.setForeground(new java.awt.Color(204, 255, 204));
        B5_1.setText("Debutant");
        B5_1.setOpaque(false);
        B5_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5_1MouseClicked(evt);
            }
        });
        jPanel1.add(B5_1);
        B5_1.setBounds(480, 250, 90, 23);

        buttonGroup5.add(B5_2);
        B5_2.setForeground(new java.awt.Color(204, 255, 204));
        B5_2.setText("Intermediaire");
        B5_2.setOpaque(false);
        B5_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5_2MouseClicked(evt);
            }
        });
        jPanel1.add(B5_2);
        B5_2.setBounds(480, 270, 130, 23);

        buttonGroup5.add(B5_3);
        B5_3.setForeground(new java.awt.Color(204, 255, 204));
        B5_3.setText("Avancée");
        B5_3.setOpaque(false);
        B5_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5_3MouseClicked(evt);
            }
        });
        B5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5_3ActionPerformed(evt);
            }
        });
        jPanel1.add(B5_3);
        B5_3.setBounds(480, 290, 90, 23);

        buttonGroup4.add(B4_1);
        B4_1.setForeground(new java.awt.Color(204, 255, 204));
        B4_1.setText("Debutant");
        B4_1.setOpaque(false);
        B4_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4_1MouseClicked(evt);
            }
        });
        jPanel1.add(B4_1);
        B4_1.setBounds(480, 120, 90, 23);

        buttonGroup4.add(B4_2);
        B4_2.setForeground(new java.awt.Color(204, 255, 204));
        B4_2.setText("Intermediaire");
        B4_2.setOpaque(false);
        B4_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4_2MouseClicked(evt);
            }
        });
        jPanel1.add(B4_2);
        B4_2.setBounds(480, 140, 130, 23);

        buttonGroup4.add(B4_3);
        B4_3.setForeground(new java.awt.Color(204, 255, 204));
        B4_3.setText("Avancée");
        B4_3.setOpaque(false);
        B4_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4_3MouseClicked(evt);
            }
        });
        jPanel1.add(B4_3);
        B4_3.setBounds(480, 160, 90, 23);

        buttonGroup3.add(B3_3);
        B3_3.setForeground(new java.awt.Color(204, 255, 204));
        B3_3.setText("Avancée");
        B3_3.setOpaque(false);
        B3_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3_3MouseClicked(evt);
            }
        });
        jPanel1.add(B3_3);
        B3_3.setBounds(80, 410, 90, 23);

        buttonGroup3.add(B3_2);
        B3_2.setForeground(new java.awt.Color(204, 255, 204));
        B3_2.setText("Intermediaire");
        B3_2.setOpaque(false);
        B3_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3_2MouseClicked(evt);
            }
        });
        jPanel1.add(B3_2);
        B3_2.setBounds(80, 390, 130, 23);

        buttonGroup3.add(B3_1);
        B3_1.setForeground(new java.awt.Color(204, 255, 204));
        B3_1.setText("Debutant");
        B3_1.setOpaque(false);
        B3_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3_1MouseClicked(evt);
            }
        });
        jPanel1.add(B3_1);
        B3_1.setBounds(80, 370, 90, 23);

        buttonGroup2.add(B2_1);
        B2_1.setForeground(new java.awt.Color(204, 255, 204));
        B2_1.setText("Debutant");
        B2_1.setOpaque(false);
        B2_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2_1MouseClicked(evt);
            }
        });
        jPanel1.add(B2_1);
        B2_1.setBounds(80, 250, 90, 23);

        buttonGroup2.add(B2_2);
        B2_2.setForeground(new java.awt.Color(204, 255, 204));
        B2_2.setText("Intermediaire");
        B2_2.setOpaque(false);
        B2_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2_2MouseClicked(evt);
            }
        });
        jPanel1.add(B2_2);
        B2_2.setBounds(80, 270, 120, 23);

        buttonGroup2.add(B2_3);
        B2_3.setForeground(new java.awt.Color(204, 255, 204));
        B2_3.setText("Avancée");
        B2_3.setOpaque(false);
        B2_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2_3MouseClicked(evt);
            }
        });
        jPanel1.add(B2_3);
        B2_3.setBounds(80, 290, 90, 23);

        buttonGroup1.add(B1_1);
        B1_1.setForeground(new java.awt.Color(204, 255, 204));
        B1_1.setText("Debutant");
        B1_1.setOpaque(false);
        B1_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1_1MouseClicked(evt);
            }
        });
        B1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1_1ActionPerformed(evt);
            }
        });
        jPanel1.add(B1_1);
        B1_1.setBounds(80, 120, 90, 20);

        buttonGroup1.add(B1_2);
        B1_2.setForeground(new java.awt.Color(204, 255, 204));
        B1_2.setText("Intermediaire");
        B1_2.setOpaque(false);
        B1_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1_2MouseClicked(evt);
            }
        });
        jPanel1.add(B1_2);
        B1_2.setBounds(80, 140, 120, 23);

        buttonGroup1.add(B1_3);
        B1_3.setForeground(new java.awt.Color(204, 255, 204));
        B1_3.setText("Avancée");
        B1_3.setOpaque(false);
        B1_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1_3MouseClicked(evt);
            }
        });
        jPanel1.add(B1_3);
        B1_3.setBounds(80, 163, 90, 20);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(25, 45, 5));
        jTextField9.setForeground(new java.awt.Color(204, 255, 204));
        jTextField9.setText("jTextField9");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9);
        jTextField9.setBounds(390, 450, 90, 20);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(25, 45, 5));
        jTextField8.setForeground(new java.awt.Color(204, 255, 204));
        jTextField8.setText("enrichir une class");
        jPanel1.add(jTextField8);
        jTextField8.setBounds(180, 450, 100, 20);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(25, 45, 5));
        jTextField7.setForeground(new java.awt.Color(204, 255, 204));
        jTextField7.setText("Les Classes");
        jPanel1.add(jTextField7);
        jTextField7.setBounds(490, 340, 110, 30);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(25, 45, 5));
        jTextField6.setForeground(new java.awt.Color(204, 255, 204));
        jTextField6.setText("Les Constructeurs");
        jPanel1.add(jTextField6);
        jTextField6.setBounds(80, 340, 120, 30);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(24, 45, 5));
        jTextField5.setForeground(new java.awt.Color(204, 255, 204));
        jTextField5.setText("objet");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(480, 220, 130, 30);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(25, 45, 5));
        jTextField4.setForeground(new java.awt.Color(204, 255, 204));
        jTextField4.setText("Les Tableaux");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(80, 220, 100, 30);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(25, 45, 5));
        jTextField3.setForeground(new java.awt.Color(204, 255, 204));
        jTextField3.setText("L'Heritage");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(480, 90, 90, 30);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(25, 45, 5));
        jTextField2.setForeground(new java.awt.Color(204, 255, 204));
        jTextField2.setText("langage java");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(80, 90, 110, 30);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(25, 45, 5));
        jTextField1.setForeground(new java.awt.Color(204, 255, 204));
        jTextField1.setText("choisissez le chapitre et le level pour commancer :");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(210, 20, 310, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vert.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(340, 450, 180, 100);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vert.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 90, 180, 100);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vert.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 220, 180, 100);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vert.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 220, 180, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vert.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 340, 180, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vert.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 340, 180, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vert.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 450, 180, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vert.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 90, 180, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solution.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 710, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void B1_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1_1MouseClicked
      
       Virus1 c= new Virus1();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B1_1MouseClicked

    private void B5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5_3ActionPerformed
       
    }//GEN-LAST:event_B5_3ActionPerformed

    private void B1_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1_2MouseClicked
     
        virus1_2 c= new virus1_2();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B1_2MouseClicked

    private void B1_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1_3MouseClicked
      
        virus1_3 c= new virus1_3();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B1_3MouseClicked

    private void B2_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2_1MouseClicked
       
        virus2 c= new virus2();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B2_1MouseClicked

    private void B2_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2_2MouseClicked
      
        virus2_2 c= new virus2_2();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B2_2MouseClicked

    private void B2_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2_3MouseClicked
      
        virus2_3 c= new virus2_3();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B2_3MouseClicked

    private void B3_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3_1MouseClicked
       
        virus3 c= new virus3();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B3_1MouseClicked

    private void B3_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3_2MouseClicked
      
        virsu3_2 c= new virsu3_2();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B3_2MouseClicked

    private void B3_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3_3MouseClicked
    
        virus3_3 c= new virus3_3();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B3_3MouseClicked

    private void B7_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7_1MouseClicked
       
       virus7 c= new virus7();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B7_1MouseClicked

    private void B7_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7_2MouseClicked
     
       virus7_2 c= new virus7_2();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B7_2MouseClicked

    private void B7_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7_3MouseClicked
       
       virus7_3 c= new virus7_3();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B7_3MouseClicked

    private void B4_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4_1MouseClicked
     
       virus4 c= new virus4();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B4_1MouseClicked

    private void B4_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4_2MouseClicked
      
       virus4_2 c= new virus4_2();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B4_2MouseClicked

    private void B4_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4_3MouseClicked
      
       virus4_3 c= new virus4_3();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B4_3MouseClicked

    private void B5_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5_1MouseClicked
     
       virus8 c= new virus8();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B5_1MouseClicked

    private void B5_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5_2MouseClicked
     
       virus5_2 c= new virus5_2();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B5_2MouseClicked

    private void B5_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5_3MouseClicked
      
       virus5_3 c= new virus5_3();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B5_3MouseClicked

    private void B6_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6_2MouseClicked
     
       virus6_2 c= new virus6_2();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B6_2MouseClicked

    private void B6_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6_1MouseClicked
   
       virus6 c= new virus6();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B6_1MouseClicked

    private void B6_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6_3MouseClicked
      
       virus6_3 c= new virus6_3();
      c.setVisible(true);
      this.hide();
    }//GEN-LAST:event_B6_3MouseClicked

    private void B7_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B7_3ActionPerformed

    private void B1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton B1_1;
    private javax.swing.JRadioButton B1_2;
    private javax.swing.JRadioButton B1_3;
    private javax.swing.JRadioButton B2_1;
    private javax.swing.JRadioButton B2_2;
    private javax.swing.JRadioButton B2_3;
    private javax.swing.JRadioButton B3_1;
    private javax.swing.JRadioButton B3_2;
    private javax.swing.JRadioButton B3_3;
    private javax.swing.JRadioButton B4_1;
    private javax.swing.JRadioButton B4_2;
    private javax.swing.JRadioButton B4_3;
    private javax.swing.JRadioButton B5_1;
    private javax.swing.JRadioButton B5_2;
    private javax.swing.JRadioButton B5_3;
    private javax.swing.JRadioButton B6_1;
    private javax.swing.JRadioButton B6_2;
    private javax.swing.JRadioButton B6_3;
    private javax.swing.JRadioButton B7_1;
    private javax.swing.JRadioButton B7_2;
    private javax.swing.JRadioButton B7_3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
